steps:
  # Build the Docker image from the project root
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deployment/docker/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/steel-rebar-predictor:latest', '.']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/steel-rebar-predictor:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'steel-rebar-predictor'
    - '--image'
    - 'gcr.io/$PROJECT_ID/steel-rebar-predictor:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'API_KEY=deacero_steel_predictor_2025_key'
    - '--port'
    - '8080'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

timeout: '1200s'
